##Add to your configuration.yaml in homeassistant
mqtt:
  sensor:
    - name: "Current Battery Capacity"
      unique_id: "current_battery_capacity"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['battCap'] }}"
      unit_of_measurement: "%"
      device_class: battery
    - name: "Current Battery Voltage"
      unique_id: "current_battery_voltage"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['battV'] }}"
      unit_of_measurement: "V"
      device_class: battery
    - name: "Current Battery Current"
      unique_id: "current_battery_current"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['battC'] }}"
      unit_of_measurement: "A"
    - name: "Current Battery TempC"
      icon: "mdi:thermometer"
      unique_id: "current_battery_tempc"
      state_topic: "NodeRenogy/state"
      value_template: "{{ float(value_json['battT']) | multiply(9/5) + int(32) }}"
      unit_of_measurement: "°F"
    - name: "Current Controller Temp"
      icon: "mdi:thermometer"
      unique_id: "current_controller_temp"
      state_topic: "NodeRenogy/state"
      value_template: "{{ float(value_json['controlT']) | multiply(9/5) + int(32) }}"
      unit_of_measurement: "°F"
    - name: "Current Solar Volts"
      unique_id: "current_solar_volts"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['solarV'] }}"
      unit_of_measurement: "V"
    - name: "Current Solar Current"
      unique_id: "current_solar_current"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['solarC'] }}"
      unit_of_measurement: "A"
    - name: "Current Solar Power"
      unique_id: "current_solar_power"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['solarP'] }}"
      unit_of_measurement: "W"
    - name: "Today Solar Power"
      unique_id: "today_solar_power"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['chgWHToday'] }}"
      unit_of_measurement: "WH"
    - name: "Today Solar Dollars"
      unique_id: "today_solar_dollar"
      state_topic: "NodeRenogy/state"
      value_template: "{{ float(value_json['chgWHToday']) | multiply(0.00009) }}"
      unit_of_measurement: "$"
    - name: "Solar Uptime"
      unique_id: "solar_uptime"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['uptime'] }}"
      unit_of_measurement: "days"
    - name: "Number of Full Battery Cycles"
      unique_id: "battery_cycles"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['totalBattFullCharges'] }}"
      unit_of_measurement: "cycles"
    - name: "Number of Battery Overcharge Cycles"
      unique_id: "battery_occycles"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['totalBattOvercharge'] }}"
      unit_of_measurement: "cycles"
    - name: "Max Charge Power Today"
      unique_id: "chgpmax_today"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['chgPMaxToday'] }}"
      unit_of_measurement: "W"
    - name: "Max Battery Voltage Today"
      unique_id: "battvmax_today"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['battVMaxToday'] }}"
      unit_of_measurement: "V"
    - name: "Min Battery Voltage Today"
      unique_id: "battvmin_today"
      state_topic: "NodeRenogy/state"
      value_template: "{{ value_json['battVMinToday'] }}"
      unit_of_measurement: "V"
    - name: "Voltage Delta"
      unique_id: "today_voltage_delta"
      state_topic: "NodeRenogy/state"
      value_template: "{{ float(value_json['solarV']) - float(value_json['battV']) }}"
      unit_of_measurement: "V"
